import React, { useMemo, useState } from "react";
import data from "./data/data.json"; // auto-generated by prebuild script

// always show EXACTLY 3 decimals (e.g., 12 → 12.000)
function fmt3(value) {
  if (value === null || value === undefined) return "";
  const raw = String(value).replace(/,/g, "").trim();
  const num = Number(raw);
  if (Number.isNaN(num)) return String(value);
  return num.toLocaleString(undefined, {
    minimumFractionDigits: 3,
    maximumFractionDigits: 3,
  });
}

export default function App() {
  const [input, setInput] = useState("");   // what the user is typing
  const [results, setResults] = useState([]);  // only updates when Search is clicked
  const [hasSearched, setHasSearched] = useState(false);

  const onSearch = () => {
    const t = input.trim().toLowerCase();
    const filtered = t
      ? data.filter((r) => (r.name || "").toLowerCase().includes(t))
      : []; // empty input → show all (change to [] if you prefer no results)
    setResults(filtered);
    setHasSearched(true);
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") onSearch();
  };

  return (
    <div style={{ padding: 20 }}>
      <h1>Point → E:N:H</h1>
      <h3>Created By Seatrium DC Team</h3>

<h4>Last Updated# 09.Dec.2025.</h4>
<h6>If the control point is the same, use the point with the prefix "A".
For example, when searching for 8045, if both 8045 and A8045 appear, select A8045.
A8045 represents the same physical point as 8045, but has a different ENH value.
The ENH of A8045 is more accurate.</h6>

      <div style={{ display: "flex", gap: 8, maxWidth: 560 }}>
        <input
          placeholder="Search by Name"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          style={{
            padding: "10px 12px",
            borderRadius: 8,
            border: "1px solid #ddd",
            width: "100%",
          }}
        />
        <button
          onClick={onSearch}
          style={{
            padding: "10px 16px",
            borderRadius: 8,
            border: "1px solid #2563eb",
            background: "#2563eb",
            color: "#fff",
            fontWeight: 700,
            cursor: "pointer",
            whiteSpace: "nowrap",
          }}
        >
          Search
        </button>
      </div>

      <table
        border="1"
        style={{ marginTop: 16, width: "100%", borderCollapse: "collapse" }}
      >
        <thead>
          <tr>
            <th style={th}>Points</th>
            <th style={th}>East</th>
            <th style={th}>North</th>
            <th style={th}>Height</th>
          </tr>
        </thead>
        <tbody>
          {(hasSearched ? results : []).map((r, i) => (
            <tr key={i}>
              <td style={td}>{r.name}</td>
              <td style={td}>{fmt3(r.east)}</td>
              <td style={td}>{fmt3(r.north)}</td>
              <td style={td}>{fmt3(r.height)}</td>
            </tr>
          ))}
          {hasSearched && results.length === 0 && (
            <tr>
              <td colSpan={4} style={{ padding: 12, color: "#c00" }}>
                No matches.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

const th = { textAlign: "left", padding: "8px", background: "#f9fbff" };
const td = { padding: "8px", borderTop: "1px solid #eee" };
