import React, { useMemo, useState } from "react";
import data from "./data/data.json"; // auto-generated by prebuild script

// always show EXACTLY 3 decimals (e.g., 12 → 12.000, 12.3 → 12.300)
function fmt3(value) {
  if (value === null || value === undefined) return "";
  const raw = String(value).replace(/,/g, "").trim();
  const num = Number(raw);
  if (Number.isNaN(num)) return String(value);

  // thousands separator ပါမယ်
  return num.toLocaleString(undefined, {
    minimumFractionDigits: 3,
    maximumFractionDigits: 3,
  });

  // thousands separator မလိုရင် အပေါ်က return ကို comment လုပ်ပြီး အောက်ကကိုသုံးပါ
  // return num.toFixed(3);
}

export default function App() {
  const [q, setQ] = useState("");

  const filtered = useMemo(() => {
    const t = q.trim().toLowerCase();
    if (!t) return data;
    return data.filter((r) => (r.name || "").toLowerCase().includes(t));
  }, [q]);

  return (
    <div style={{ padding: 20 }}>
      <h1>Point → E:N:H</h1>
      <h3>Created By Seatrium DC Team</h3>

      <input
        placeholder="Search by Name"
        value={q}
        onChange={(e) => setQ(e.target.value)}
        style={{
          padding: "10px 12px",
          borderRadius: 8,
          border: "1px solid #ddd",
          width: "100%",
          maxWidth: 420,
        }}
      />

      <table
        border="1"
        style={{ marginTop: 16, width: "100%", borderCollapse: "collapse" }}
      >
        <thead>
          <tr>
            <th style={th}>Points</th>
            <th style={th}>East</th>
            <th style={th}>North</th>
            <th style={th}>Height</th>
          </tr>
        </thead>
        <tbody>
          {filtered.map((r, i) => (
            <tr key={i}>
              <td style={td}>{r.name}</td>
              <td style={td}>{fmt3(r.east)}</td>
              <td style={td}>{fmt3(r.north)}</td>
              <td style={td}>{fmt3(r.height)}</td>
            </tr>
          ))}
          {filtered.length === 0 && (
            <tr>
              <td colSpan={4} style={{ padding: 12, color: "#c00" }}>
                No matches.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

const th = { textAlign: "left", padding: "8px", background: "#f9fbff" };
const td = { padding: "8px", borderTop: "1px solid #eee" };
